### ISSUE TITLE
Shorter format for matching

### ISSUE THREAD

**Issue by lexnederbragt** [mozillascience/studyGroupLessons#1]
Why use

```
awk '{if (index($3, "earth") != 0) print $3}' volcano_observations.dat
earthquakes
```

when you can use

```
awk '$3 ~ /earth/ {print $3}' volcano_observations.dat
```

Same with this one: why use

```
awk '{if (NR > 1 && index($3, "e") != 0) print $0}' volcano_observations.dat
```

when this suffices:

```
awk 'NR >1 && $3 ~ /e/' volcano_observations.dat
```

Is it for educational purposes, because the long version is easier to understand than the short version?

**Comment by katieannemills** [comment]
Interesting point! I think the longer version is easier to read, but I admit that's just an opinion. The lesson worked well as is; maybe it's best for beginners to be a bit more explicit? Too much regex too early can be really daunting. What do you think?

**Comment by lexnederbragt** [comment]
I just found out one could also use

```
awk 'NR >1 && $3 ~ "e"' volcano_observations.dat
```

which has less of a regex feel, so is perhaps more natural, and has the benefit of shortness and being easy to read.

**Comment by katieannemills** [comment]
since we've switched to a subrepo format for lessons, content issues are best opened in the respective lesson repositories.

![unnamed](https://cloud.githubusercontent.com/assets/1896943/7894643/62bf5bfa-0622-11e5-95ed-02e5c09b6473.png)
