### ISSUE TITLE
Best way to organize and promote lessons

### ISSUE THREAD

**Issue by katieannemills** [mozillascience/studyGroupLessons#2]
@wking mentioned some great ideas for how best to organize and promote study group lessons over on https://github.com/swcarpentry/board/pull/27 - to summarize their suggestions:
- keep the lessons themselves out of the study-group repository, since maintaining a lesson on awk and keeping track of study groups around the world teaching scientists our tooling seem like two different tasks. 
- linking to lessons by title seems better than linking to groups. At least, there should be a way to answer “what are the most popular hour-long lessons talking about awk?” (or whatever).

**Comment by katieannemills** [comment]
heya @wking, continuing on from our other thread:
- hmmm, I definitely see what you mean about maintaining lessons and linking groups to be different tasks. I guess I put them both under the umbrella of 'pointing to content'. The issue is that we we serve two distinct groups: those who aren't into maintaining their own repos, and those who are. For those who aren't, I wanted to make things as easy as possible for them; for those who do, I wanted to direct traffic and attention to their projects, by linking out to them.
- I really like the idea of curating together a list of links to lessons by topic; feel free to PR :) or I can take a run at it. I would however maintain the list of links by location too, to draw attention to all the hard work these groups are doing and to help others find and link up with them (rather than starting their own when there's already one right next door).

**Comment by wking** [comment]
On Mon, Mar 23, 2015 at 04:05:34PM -0700, Bill Mills wrote:

> - linking to lessons by title seems better than linking to
>   groups. At least, there should be a way to answer “what are the
>   most popular hour-long lessons talking about awk?” (or whatever).

So it's hard to handle the “hour long” part of this cleanly, but if
you package up your lessons using Bower, you can just piggy-back on
their keyword search and star system [1,2] to get lessons about awk.
For a sketch of this approach from SWC's 2014 sprint, see [3](although that was focused on dependency resolution, which is
orthogonal to the discoverability issue I'm suggesting Bower for
here).  I don't _think_ getting Bower installed on lesson-maintainer
boxes will be too high a bar (but I'd appreciate more feedback here).
Once you find a lesson using Bower's search, you'll end up at the
lesson's repository, so folks just _consuming_ the lesson shouldn't
need to install Bower (although they can if they want to search
packages/lessons from the command line).

**Comment by wking** [comment]
On Mon, Mar 23, 2015 at 04:11:21PM -0700, Bill Mills wrote:

> I would however maintain the list of links by location too, to draw
> attention to all the hard work these groups are doing and to help
> others find and link up with them (rather than starting their own
> when there's already one right next door).

Right, I think you want one collection of “science/computing study
groups that you can look at for inspiration (or to join)”.  And then
another collection of “hour-ish lessons on assorted science/computing
topics that you can learn from or use as a basis for teaching others”.
I'd keep things going the way you currently are in this repository for
the first list, and then have folks push Bower packages and use the
Bower search enging for the second list.

**Comment by katieannemills** [comment]
Cool ideas! I think we should take a run at examining the bower workflow; my gut says this is very complicated for most people (esp when thinking about contributing back), but I'm very willing to be proven wrong. I wrote up the awk lesson as straight md, no jekyll, no fancy shmancy anything, so that the barrier to participation was as low as possible (in this case, elementary git and md), which is a design feature I really want to keep - but let's give a package manager a try. @wking, let's collaborate on making a demo of this workflow.

**Comment by wking** [comment]
Poking around from [1](https://github.com/jlord/git-it) led me to workshopper [2](which is really
cool) and http://nodeschool.io/.  nodeschool is pretty much what
you're trying to do here (both for currating lessons and for building
communities around workshops).  Maybe we should see about spinning up
their infrastructure for our audience?  Their static frontend has
notes about local instances [3](https://github.com/nodeschool/nodeschool.github.io#running-the-app-locally).  It looks like they're pulling their
event data from Google Docs [4](https://github.com/nodeschool/nodeschool.github.io/blob/42b7f9d2b1e31b143aead969fcbaaee99bb7f6ba/js/events.js#L8), which I find questionable, but where
we store the data doesn't really matter.  It also looks like they
manually currate a list of workshoppers, so the Bower-listing idea may
still have legs.

**Comment by wking** [comment]
On Mon, Mar 23, 2015 at 04:44:11PM -0700, Bill Mills wrote:

> … let's collaborate on making a demo of this workflow.

Sure.  Drop the awk lesson in a repository somewhere, and I'll PR it
with a bower.json.

**Comment by katieannemills** [comment]
have at'r: https://github.com/BillMills/awk-lesson

also: man I feel dumb for not thinking of nodeschool, they're awesome and you're right, a pretty close cousin of what we're doing here. I would contrast the two by saying that a Study Group is intended to be _super easy_ to set up and run, with a minimum of overhead, but nevertheless nodeschool is an awesome example of something very similar and we should definitely be learning from them - in fact, why don't I ping them right now...

**Comment by katieannemills** [comment]
gone to a submod structure for this - allows people to retain their own content repos, keeps this one from blowing up, relatively technically simple.
