### ISSUE TITLE
Melbourne and Brisbane pins

### ISSUE THREAD

**Issue by DamienIrving** [mozillascience/studyGroupLessons#54]
@BillMills Can we get the University of Melbourne, Swinburne and Brisbane Hacky Hours up on the map?
http://melbourne.resbaz.edu.au/hackyhour
http://www.thehackerwithin.org/swinburne/
http://samhames.github.io/hackyhour-stlucia/about/

(cc @samhames @drarnakarick )

**Comment by SamHames** [comment]
And Griffith University too please - https://hackyhourgriffith.wordpress.com/

**Comment by katieannemills** [comment]
Done and done, and the honor is mine! Are the leads of these groups aware of:
- the monthly community calls for Study Group leads worldwide, announced on this mailing list: https://mail.mozilla.org/listinfo/msl-study-groups
- the [Study Group Handbook](http://mozillascience.github.io/studyGroupHandbook/index.html), our repository of collective wisdom on running events like these.

The next community call where I ask Study Group leaders to get together and discuss how things are going is (unfortunately) at 4 AM Melbourne time this Saturday (sorry) - but the number one thing I want to discuss this month, is starting regional community calls to avoid this problem in future. If the Australia community has can identify someone to lead these calls at a time that is a little more reasonable for the region, I'd be happy to join in to get things going.

The Handbook is a result of my study of worldwide efforts at meetups such as these - but it is a work in progress. I'm very much looking for contributions, comments, and PRs against this work; let me know what your communities have learned, so we can share that back with Study Groups worldwide!

**Comment by katieannemills** [comment]
Oh also - I dropped pins on the general regions you mentioned, but feel free to send me lat/long coords for more precise pins, if you like!

**Comment by amandamiotto** [comment]
Thanks Sam!

Hey Bill, I'm one of the Hackers at Griffith uni (https://hackyhourgriffith.wordpress.com/). We've got buddies across the sea as well- Auckland in New Zealand http://uoa-eresearch.github.io/HackyHour/ via Sina Masoud-Ansari

**Comment by katieannemills** [comment]
thanks @amandamiotto - Auckland is on the map! Again, would love to plug all the groups in the region into the wider community even more, by getting feedback on the [Handbook](http://mozillascience.github.io/studyGroupHandbook/index.html), hearing your lessons learned on how other people can start Hacky Hours or Study Groups, or by checking out and contributing to the [Lesson Issue Index](http://mozillascience.github.io/studyGroupHandbook/lessons.html#lessons) if any group ever leads a demo-style lesson or workshop. Thanks again!
